name: Using VM for workflow

on:   
 
 workflow_dispatch:

 push:
    branches:
        - main
        - 'feature/*'
           
jobs:
    docker:
      strategy:
        fail-fast: false # to stop the running jobs when the job is failure
        matrix:
          os: [self-hosted,windows-latest]
          exclude: 
            - os: windows-latest

      runs-on: ${{ matrix.os }}
      environment: trial

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            # IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
            # TAG: ${{ secrets.TAG }}
          run: |
            echo $DOCKER_PASSWORD | docker login -u  $DOCKER_USERNAME --password-stdin
        
        - name: Build Docker image
          run: |
            docker build -t mkk-nginx .

        - name: Tag the Image
          run: |
            docker tag  mkk-nginx:latest "$DOCKER_USERNAME/mkk-nginx:latest"
        
        - name: Push the Image to Dockerhub
          run: |
            docker push "$DOCKER_USERNAME/mkk-nginx:latest"

        # - name: Creating a container

    

        