name: Using VM for workflow

on:   
 
 workflow_dispatch:

 push:
    branches:
        - main
        - 'feature/*'
           
jobs:
    deploy:
      strategy:
        fail-fast: false # to stop the running jobs when the job is failure
        matrix:
          os: [self-hosted, ubuntu-latest, windows-latest]
          exclude: 
            - os: windows-latest

      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}