name: Using VM for workflow

on:   
 
 workflow_dispatch:

jobs:
    deploy:
        strategy:
          matrix:
            os: [ self-Hosted, ubuntu-latest,windows-latest]
            exclude: #excluding windows-latest os from the config
              - os: windows-latest
        runs-on: ${{matrix.os}}
        steps:
         - name: Checkout repo
           uses: actions/checkout@v4

         - name: Login to DockerHub
           uses: docker/login-action@v2
           with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
           


            
              